### PR TITLE
Show department name in authenticating info

### PR DESCRIPTION
**Pull request by katrina376**
Also fix the displacement of the buttons (but not sure if the problem is really solved) and add new status of buttons. I'm wondering whether the unauthorized status should be considered or not. Should I make the unauthorized message un-dismissible?

### CODE REVIEW

**Comment by azdkj532** [comment]
It reports error on iPad mini with iOS 9.3.1, but it works fine on iPad mini2 with iOS 10.1.1 .

**Comment by azdkj532** [comment]
```
TypeError: it of $$ is not a function. (In 'it of $$('button')', 'it of $$' is undefined)
全域代碼 — main.js:94
````

**Comment by azdkj532** [comment]
Please help us~
@andy0130tw @bobby1030 @elantris
